version: '3.8'
services:
    app:
        build:
            context: .
        image: laravel-app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 8080:9000
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root
    db:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
